{% set name = "geoarray" %}
{% set version = "0.12.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e07cc1b831500ebb3bd2c0f5b8459f49b4a2386c724e5312a462c5d587ba53c7

build:
  number: 0
  skip: true  # [py<36]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
    - setuptools
    - setuptools-git
  run:
    - cartopy
    - dill
    - gdal >=2.1.0
    - matplotlib-base
    - numpy
    - pandas
    - pyepsg  # optional dependency of cartopy, needed by geoarray
    - py-tools-ds >=0.14.35
    - python
    - scikit-image
    - shapely

test:
  imports:
    - geoarray
    - geoarray.baseclasses
    - geoarray.masks
    - geoarray.metadata
    - geoarray.subsetting
  commands:
    - pip check
  requires:
    - pip


about:
  home: https://pypi.org/project/geoarray/
  summary: Fast Python interface for geodata - either on disk or in memory.
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mxr-conda
    - danschef
    - rluria14
    - ndmaxar
    - RyanHackney
