{% set name = "geoarray" %}
{% set version = "0.15.8" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: af54f795563dca0ae32bd5c8625fdbef2aebc90ed9c73c11f87c41c381b8cf5c

build:
  number: 0
  skip: true  # [py<36]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
    - setuptools
    - setuptools-git
  run:
    - cartopy
    - dill
    - fontconfig >=2.13.1,<2.13.96  # [osx and py37]  # intermediate fix for https://github.com/kb47/pdf-poppler/issues/2#issuecomment-1063521221
    - gdal >=2.1.0
    - matplotlib-base
    - numpy
    - pandas
    - pyepsg  # optional dependency of cartopy, needed by geoarray
    - py-tools-ds >=0.18.0
    - python
    - scikit-image
    - shapely

test:
  imports:
    - geoarray
    - geoarray.baseclasses
    - geoarray.masks
    - geoarray.metadata
    - geoarray.subsetting
  commands:
    - pip check
  requires:
    - pip


about:
  home: https://pypi.org/project/geoarray/
  summary: Fast Python interface for geodata - either on disk or in memory.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mxr-conda
    - danschef
    - rluria14
    - ndmaxar
    - RyanHackney
