{% set name = "geoarray" %}
{% set version = "0.12.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9107089cc83bb5d000253d2c880a91ba5b5a58d741ddf48c3c8423a3b3a6c3f2

build:
  number: 0
  skip: true  # [py<36]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
    - setuptools
    - setuptools-git
  run:
    - cartopy
    - dill
    - gdal >=2.1.0
    - matplotlib-base
    - numpy
    - pandas
    - pyepsg  # optional dependency of cartopy, needed by geoarray
    - py-tools-ds >=0.14.35
    - python
    - scikit-image
    - shapely

test:
  imports:
    - geoarray
    - geoarray.baseclasses
    - geoarray.masks
    - geoarray.metadata
    - geoarray.subsetting
  commands:
    - pip check
  requires:
    - pip


about:
  home: https://pypi.org/project/geoarray/
  summary: Fast Python interface for geodata - either on disk or in memory.
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mxr-conda
    - danschef
    - rluria14
    - ndmaxar
    - RyanHackney
