{% set name = "geoarray" %}
{% set version = "0.8.34" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c6449c00ffcb2ac749d33fd2e7817123163f358b8a3f031992dcbf815483cdb5

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - dask >=0.15.0
    - pip
    - python
    - matplotlib-base
  run:
    - dask >=0.15.0
    - dill
    - folium
    - gdal >=2.1.0
    - geojson
    - matplotlib-base
    - mpld3
    - numpy
    - pandas
    - py-tools-ds >=0.14.35
    - python
    - scikit-image
    - shapely
    - six

test:
  imports:
    - geoarray

about:
  home: https://pypi.org/project/geoarray/
  summary: Fast Python interface for geodata - either on disk or in memory.
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rluria14
    - ndmaxar
    - RyanHackney
    - danschef
